### PR TITLE
Add validation for Nigerian states

### PR DESCRIPTION
**Pull request by jeddtony**
I added validation for Nigerian states, this feature would be very useful for the Laravel community here in Nigeria

### CODE REVIEW

**Comment by ssx** [comment]
@jeddtony hi! This is a great PR, however I think it would be better suited in its own package, something like states-nigeria or ng-states. This package is for US ones only.

Would you be happy for them to be moved to a new repository?

**Comment by jeddtony** [comment]
Certainly.

If moving them to a new repository would serve the  purpose better, why not.

**Comment by ssx** [comment]
Awesome, I'll create the new repo early this week and add you as a collaborator you have the required access that you need. Thanks again Jedidiah!

**Comment by jeddtony** [comment]
You're welcome Scott

**Comment by jeddtony** [comment]
Good day, Scott,

Hope your day is fine.

I just want to remind you about what we discussed earlier about making me a collaborator. 

Thanks in anticipation

**Comment by ssx** [comment]
@jeddtony apologies for the delay in getting back to you on this. If you update your branch with the latest changes here, we'll get it merged in to this one.

**Comment by jeddtony** [comment]
Hi @ssx 

I have updated the PR with the latest changes. Please feel free to let me know if there are modifications that I need to make

**Review by ssx — APPROVED** [review]

**Review by ssx — APPROVED** [review]

**Pull request merged**
