### PR TITLE
Add Mexico states

### PR DESCRIPTION
**Pull request by mikemand**
Since you're already doing Canada, why not Mexico too?

Data from: https://www.iso.org/obp/ui/#iso:code:3166:MX

(Edit: I forgot to stage the tests, d'oh!)

### CODE REVIEW

**Comment by ssx** [comment]
@mikemand that looks great, if @tylercd100 has no issues I'll get it merged.

**Comment by mikemand** [comment]
Hi @ssx,

Thanks! I just read somewhere not too long after opening this PR that the two-letter codes for Mexico's states (and one federal district) are not official, and according to [ISO 3166-2](https://www.iso.org/obp/ui/#iso:code:3166:MX), they only have three-letter codes.

I'm not sure if I should change this to the three-letter codes, or leave it as is...

**Comment by ssx** [comment]
That's a pretty good question. If the official ones are three char then I
think it's better to use those.

**Comment by mikemand** [comment]
Hi @ssx,

I've updated to use ISO 3166-2 as my data source. A couple of the state names changed (I'm looking at you, Ciudad de México), but that shouldn't be a problem since they are more official than a Wikipedia template. 😆

**Comment by tylercd100** [comment]
I agree that we should use the 3-character codes. This all looks good to me. I'll merge it soon. :)

**Comment by tylercd100** [comment]
@mikemand Thank you for your PR! :)

**Comment by mikemand** [comment]
Thank you both for the very helpful validation rule. 😃

**Pull request merged**
